# --- FONT ---
font_family Sarasa Mono
font_size 11.5

# --- BASE COLORS ---
background #1b2233
foreground #e6f2ff

# --- CURSOR ---
cursor #8ec5ff
cursor_shape beam
cursor_blink_interval 0.6

# --- SELECTION ---
selection_background #2a3550
selection_foreground #ffffff

# --- TERMINAL COLORS ---
color0  #20283c
color1  #ff9bdc
color2  #8ec5ff
color3  #b7dcff
color4  #5fa8ff
color5  #c792ea
color6  #89ddff
color7  #e6f2ff

color8  #3a4666
color9  #ffb7e9
color10 #a6d6ff
color11 #d0eaff
color12 #82bbff
color13 #ddb7ff
color14 #b6f0ff
color15 #ffffff

# --- SOFTNESS ---
background_opacity 0.95
window_padding_width 14
